
DROP DATABASE MIA;

-- Create the User table
DROP TABLE IF EXISTS Annotation;
DROP TABLE IF EXISTS Permission;
DROP TABLE IF EXISTS Sub_Label;
DROP TABLE IF EXISTS Label;
DROP TABLE IF EXISTS Image;
DROP TABLE IF EXISTS Admin;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Collection;
